setblock ~ 63 ~ light_block 15
execute @s ~ 62 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 61 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 60 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 59 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 58 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 57 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 56 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 55 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 54 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 53 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 52 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 51 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 50 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 49 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 48 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 47 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 46 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 45 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 44 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 43 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 42 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 41 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 40 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 39 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 38 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 37 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15
execute @s ~ 36 ~ detect ~ ~ ~ water 0 setblock ~~~ light_block 15