summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree
summon minecraft:armor_stand ~ ~ ~ avoid_jungle_wood JungleTree