summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
summon minecraft:armor_stand ~ ~ ~ despawnable lights
