execute @e[name=main,scores={seq_id=5,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut2
execute @e[name=main,scores={seq_id=8,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut3
execute @e[name=main,scores={seq_id=9,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut4
execute @e[name=main,scores={seq_id=12,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut5
execute @e[name=main,scores={seq_id=14,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut6
execute @e[name=main,scores={seq_id=16,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut7
execute @e[name=main,scores={seq_id=18,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut8
execute @e[name=main,scores={seq_id=20,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut9
execute @e[name=main,scores={seq_id=22,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut10
execute @e[name=main,scores={seq_id=23,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut11
execute @e[name=main,scores={seq_id=25,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut12
execute @e[name=main,scores={seq_id=27,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut13
execute @e[name=main,scores={seq_id=29,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut14
execute @e[name=main,scores={seq_id=30,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut15
#blobert wating clock dialogue
#execute @e[name=main,scores={seq_id=31,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut16
execute @e[name=main,scores={seq_id=33,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:npc_blobert] @a[tag=dia_spam] tut17
execute @e[name=main,scores={seq_id=34,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:npc_blobert] @a[tag=dia_spam] tut18
execute @e[name=main,scores={seq_id=35,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut19
execute @e[name=main,scores={seq_id=36,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut20
#execute @e[name=main,scores={seq_id=38,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:npc_hortence] @a[tag=dia_spam] tut21
execute @e[name=main,scores={seq_id=40,seconds_timer=20..}] ~~~ dialogue open @e[type=chum:mercorgi_npc] @a[tag=dia_spam] tut22
