execute @e[name=main,scores={cotd_random=0},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_angler_cotd
execute @e[name=main,scores={cotd_random=1},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_butterfly_cotd
execute @e[name=main,scores={cotd_random=2},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_chameleon_cotd
execute @e[name=main,scores={cotd_random=3},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_crab_cotd
execute @e[name=main,scores={cotd_random=4},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_crawler_cotd
execute @e[name=main,scores={cotd_random=5},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_cuddle_cotd
execute @e[name=main,scores={cotd_random=6},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_eclipse_cotd
execute @e[name=main,scores={cotd_random=7},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_feather_cotd
execute @e[name=main,scores={cotd_random=8},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_kelp_cotd
execute @e[name=main,scores={cotd_random=9},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_parrot_cotd
execute @e[name=main,scores={cotd_random=10},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_piranja_cotd
execute @e[name=main,scores={cotd_random=11},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_pod_cotd
execute @e[name=main,scores={cotd_random=12},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_puffer_cotd
execute @e[name=main,scores={cotd_random=13},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_rocket_cotd
execute @e[name=main,scores={cotd_random=14},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_royal_cotd
execute @e[name=main,scores={cotd_random=16},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_shark_cotd
execute @e[name=main,scores={cotd_random=17},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_slug_cotd
execute @e[name=main,scores={cotd_random=18},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_spike_cotd
execute @e[name=main,scores={cotd_random=19},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_spook_cotd
execute @e[name=main,scores={cotd_random=20},tag=tut_finished] ~~~ event entity @e[type=chum:conversion_system] chum:set_toad_cotd