give @s tsu:kinetic_axe
give @s tsu:concussion_hammer
give @s tsu:rocket_axe
give @s tsu:laser_sword
give @s tsu:laser_blaster
give @s tsu:scatter_blaster
give @s tsu:creeper_canon
give @s tsu:omni_gun
give @s tsu:lightning_gun
give @s tsu:longsword
give @s tsu:fire_saw
give @s tsu:blaster_glove
give @s tsu:ion_gun
give @s tsu:pulse_gun
give @s tsu:laser_bow